// Code generated by goctl. DO NOT EDIT.
package types

type AuditLog struct {
	TenantID     string `json:"tenant_id"`     // 租户ID，必填
	UserID       string `json:"user_id"`       // 用户ID，必填
	Username     string `json:"username"`      // 用户名
	Action       string `json:"action"`        // 操作名称（如CREATE_VM）
	ResourceType string `json:"resource_type"` // 资源类型（如VM、DB）
	ResourceID   string `json:"resource_id"`   // 操作对象ID
	ResourceName string `json:"resource_name"` // 操作对象名称
	Result       string `json:"result"`        // 操作结果（success/fail）
	Message      string `json:"message"`       // 失败或详细信息
	ClientIP     string `json:"client_ip"`     // 客户端IP
	FromService  string `json:"from_service"`  // 来源服务
	TraceID      string `json:"trace_id"`      // 链路追踪ID
	CreatedAt    int64  `json:"created_at"`    // 时间戳（毫秒）
}

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type ExportRequest struct {
	Query struct {
		TenantID     string `form:"tenant_id"`              // 租户ID，必填
		UserID       string `form:"user_id,optional"`       // 用户ID，可选
		Username     string `form:"username,optional"`      // 用户名，可选
		Action       string `form:"action,optional"`        // 操作类型
		ResourceType string `form:"resource_type,optional"` // 资源类型
		ResourceID   string `form:"resource_id,optional"`   // 资源ID
		Result       string `form:"result,optional"`        // 操作结果
		Keyword      string `form:"keyword,optional"`       // 关键字模糊搜索
		StartTime    int64  `form:"start_time,optional"`    // 起始时间戳（毫秒）
		EndTime      int64  `form:"end_time,optional"`      // 结束时间戳（毫秒）
		Page         int    `form:"page,default=1"`         // 分页页码，默认1
		PageSize     int    `form:"page_size,default=20"`   // 每页大小，默认20
	} `json:"query"` // 查询条件
	Format      string `json:"format"`       // 导出格式（csv/json）
	CallbackURL string `json:"callback_url"` // 回调通知地址
}

type ExportResponse struct {
	BaseResponse
	TaskID string `json:"task_id"` // 导出任务ID
}

type QueryRequest struct {
	TenantID     string `form:"tenant_id"`              // 租户ID，必填
	UserID       string `form:"user_id,optional"`       // 用户ID，可选
	Username     string `form:"username,optional"`      // 用户名，可选
	Action       string `form:"action,optional"`        // 操作类型
	ResourceType string `form:"resource_type,optional"` // 资源类型
	ResourceID   string `form:"resource_id,optional"`   // 资源ID
	Result       string `form:"result,optional"`        // 操作结果
	Keyword      string `form:"keyword,optional"`       // 关键字模糊搜索
	StartTime    int64  `form:"start_time,optional"`    // 起始时间戳（毫秒）
	EndTime      int64  `form:"end_time,optional"`      // 结束时间戳（毫秒）
	Page         int    `form:"page,default=1"`         // 分页页码，默认1
	PageSize     int    `form:"page_size,default=20"`   // 每页大小，默认20
}

type QueryResponse struct {
	Total int        `json:"total"` // 总记录数
	List  []AuditLog `json:"list"`  // 日志列表
}
