// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auditlog "codexie.com/auditlog/internal/handler/auditlog"
	"codexie.com/auditlog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/export",
				Handler: auditlog.ExportLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/query",
				Handler: auditlog.QueryLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/report",
				Handler: auditlog.ReportLogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/audit"),
	)
}
